
mysql:
  addr: "127.0.0.1:3306"
  dsn: "root:Hitosea@123..@tcp(127.0.0.1:3306)/coss?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8mb4"
  readDSN:
    - "root:Hitosea@123..@tcp(127.0.0.1:3306)/coss?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8mb4"
  idleTimeout: "4h"
  queryTimeout: "800ms"
  execTimeout: "800ms"
  tranTimeout: "100ms"

