
mysql:
  addr: "127.0.0.1:33066"
  dsn: "root:888888@tcp(127.0.0.1:33066)/coss?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  readDSN:
    - "root:123456@tcp(127.0.0.1:33066)/coss?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  idleTimeout: "4h"
  queryTimeout: "800ms"
  execTimeout: "800ms"
  tranTimeout: "100ms"

