log:
  stdout: true
  v: -1
  file: "logs/app.log"
  format: "console" # console、json

mysql:
  addr: "mysql:3306"
  dsn: "root:888888@tcp(mysql:33066)/coss?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  readDSN:
    - "root:Hitosea@123..@tcp(mysql:3306)/coss?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  idleTimeout: "4h"
  queryTimeout: "800ms"
  execTimeout: "800ms"
  tranTimeout: "100ms"

redis:
  name: "user-bff"
  proto: "tcp"
  addr: "172.16.38.91:6379"
  dialTimeout: "1s"
  readTimeout: "1s"
  writeTimeout: "1s"
  idleTimeout: "10s"

grpc:
  addr: "0.0.0.0:10001"

# 注册本服务
register:
  name: "relation_service"
  addr: "注册中心地址"
  tags: ["关系服务", "relation_service"]

