log:
  stdout: true
  v: -1
  file: "logs/app.log"
  format: "console" # console、json

mysql:
  addr: "127.0.0.1:33066"
  dsn: "root:888888@tcp(127.0.0.1:33066)/coss?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  readDSN:
    - "root:123456@tcp(127.0.0.1:33066)/coss?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  idleTimeout: "4h"
  queryTimeout: "800ms"
  execTimeout: "800ms"
  tranTimeout: "100ms"

redis:
  name: "user-bff"
  proto: "tcp"
  addr: "172.16.38.91:6379"
  dialTimeout: "1s"
  readTimeout: "1s"
  writeTimeout: "1s"
  idleTimeout: "10s"

grpc:
  addr: "127.0.0.1:10002"

# 注册本服务
register:
  name: "user_service"
  addr: "注册中心地址"
  tags: ["消息服务", "user_service"]

