version: '3.9'
services:
  mysql:
    image: mysql:5.7
    volumes:
    - ./data/var/lib/mysql:/var/lib/mysql
    command: [
      '--character-set-server=utf8mb4',
    ]
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Hitosea@123.."
      MYSQL_DATABASE: coss
      MYSQL_USER: coss
      MYSQL_PASSWORD: "Hitosea@123.."
      MYSQL_TCP_PORT: '3306'
      MYSQL_ROOT_HOST: '%'
#      MARIADB_AUTO_UPGRADE: 'true'
#      MARIADB_DISABLE_UPGRADE_BACKUP: 'true'
    healthcheck:
      test: mysqladmin ping -h mysql -P 3306 -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
  gateway:
    image: hub.hitosea.com/cossim/gateway-interface
#    volumes:
#    - ./data/interface/gateway/config:/config:ro
    ports:
    - "8080:8080"
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  msg_bff:
    image: hub.hitosea.com/cossim/msg-interface
#    volumes:
#    - ./data/interface/msg/config:/app/config/:ro
    expose:
    - "8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  relation_bff:
    image: hub.hitosea.com/cossim/relation-interface
#    volumes:
#    - ./data/interface/relation/config:/app/config/:ro
    expose:
    - "8082"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  user_bff:
    image: hub.hitosea.com/cossim/user-interface
#    volumes:
#    - ./data/interface/user/config:/app/config/:ro
    expose:
    - "8083"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  msg_service:
    image: hub.hitosea.com/cossim/msg-service
#    volumes:
#    - ./data/service/msg/config:/app/config/:ro
    expose:
    - "10000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  relation_service:
    image: hub.hitosea.com/cossim/relation-service
#    volumes:
#    - ./data/service/relation/config:/app/config/:ro
    expose:
    - "10001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  user_service:
    image: hub.hitosea.com/cossim/user-service
#    volumes:
#    - ./data/service/user/config:/app/config/:ro
    expose:
    - "10002"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure