definitions:
  http.addBlacklistRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.addFriendRequest:
    properties:
      e2eublic_key:
        type: string
      msg:
        type: string
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.confirmFriendRequest:
    properties:
      p2public_key:
        type: string
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.deleteBlacklistRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.deleteFriendRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.joinGroupRequest:
    properties:
      group_id:
        type: integer
    required:
    - group_id
    type: object
  http.switchUserE2EPublicKeyRequest:
    properties:
      public_key:
        type: string
      user_id:
        type: string
    required:
    - public_key
    - user_id
    type: object
  utils.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  title: coss-relation-bff服务
paths:
  /relation/add_blacklist:
    post:
      consumes:
      - application/json
      description: 添加黑名单
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.addBlacklistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 添加黑名单
  /relation/add_friend:
    post:
      consumes:
      - application/json
      description: 添加好友
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.addFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 添加好友
  /relation/blacklist:
    get:
      consumes:
      - application/json
      description: 黑名单
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 黑名单
  /relation/confirm_friend:
    post:
      consumes:
      - application/json
      description: 确认添加好友
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.confirmFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 确认添加好友
  /relation/delete_blacklist:
    post:
      consumes:
      - application/json
      description: 删除黑名单
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.deleteBlacklistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 删除黑名单
  /relation/delete_friend:
    post:
      consumes:
      - application/json
      description: 删除好友
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.deleteFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 删除好友
  /relation/friend_list:
    get:
      consumes:
      - application/json
      description: 好友列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 好友列表
  /relation/group/join:
    post:
      consumes:
      - application/json
      description: 加入群聊
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.joinGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 加入群聊
  /user/switch/e2e/key:
    post:
      consumes:
      - application/json
      description: 交换用户端到端公钥
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.switchUserE2EPublicKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - BearerToken: []
      summary: 交换用户端到端公钥
swagger: "2.0"
