definitions:
  http.ManageFriendRequest:
    properties:
      e2e_public_key:
        type: string
      status:
        type: integer
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.addBlacklistRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.addFriendRequest:
    properties:
      e2e_public_key:
        type: string
      msg:
        type: string
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.approveJoinGroupRequest:
    properties:
      group_id:
        type: integer
      status:
        type: integer
      user_id:
        type: string
    required:
    - group_id
    - status
    - user_id
    type: object
  http.deleteBlacklistRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.deleteFriendRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  http.joinGroupRequest:
    properties:
      group_id:
        type: integer
    required:
    - group_id
    type: object
  http.quitGroupRequest:
    properties:
      group_id:
        type: integer
    required:
    - group_id
    type: object
  http.removeUserFromGroupRequest:
    properties:
      group_id:
        type: integer
      user_id:
        type: string
    required:
    - group_id
    - user_id
    type: object
  http.switchUserE2EPublicKeyRequest:
    properties:
      public_key:
        type: string
      user_id:
        type: string
    required:
    - public_key
    - user_id
    type: object
  utils.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  title: coss-relation-bff服务
paths:
  /relation/delete_blacklist:
    post:
      consumes:
      - application/json
      description: 删除黑名单
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.deleteBlacklistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 删除黑名单
  /relation/group/join:
    post:
      consumes:
      - application/json
      description: 加入群聊
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.joinGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 加入群聊
  /relation/group/manage_join_group:
    post:
      consumes:
      - application/json
      description: 管理加入群聊
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.approveJoinGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 管理加入群聊
  /relation/group/member:
    get:
      description: 群聊成员列表
      parameters:
      - description: 群聊ID
        in: query
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 群聊成员列表
  /relation/group/quit:
    post:
      consumes:
      - application/json
      description: 退出群聊
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.quitGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 退出群聊
  /relation/group/remove:
    post:
      consumes:
      - application/json
      description: 将用户从群聊移除
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.removeUserFromGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 将用户从群聊移除
  /relation/group/request_list:
    get:
      description: 群聊申请列表
      parameters:
      - description: 群聊ID
        in: query
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 群聊申请列表
  /relation/user/add_blacklist:
    post:
      consumes:
      - application/json
      description: 添加黑名单
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.addBlacklistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 添加黑名单
  /relation/user/add_friend:
    post:
      consumes:
      - application/json
      description: 添加好友
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.addFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 添加好友
  /relation/user/blacklist:
    get:
      description: 黑名单
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 黑名单
  /relation/user/delete_friend:
    post:
      consumes:
      - application/json
      description: 删除好友
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.deleteFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 删除好友
  /relation/user/friend_list:
    get:
      description: 好友列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 好友列表
  /relation/user/manage_friend:
    post:
      consumes:
      - application/json
      description: 管理好友请求
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.ManageFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 管理好友请求
  /relation/user/request_list:
    get:
      description: 好友申请列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 好友申请列表
  /relation/user/switch/e2e/key:
    post:
      consumes:
      - application/json
      description: 交换用户端到端公钥
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.switchUserE2EPublicKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - BearerToken: []
      summary: 交换用户端到端公钥
swagger: "2.0"
