log:
  stdout: true
  v: -1
  file: "logs/app.log"
  format: "console" # console、json

mysql:
  addr: "172.16.38.91:3306"
  dsn: "root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  readDSN:
    - "root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  idleTimeout: "4h"
  queryTimeout: "800ms"
  execTimeout: "800ms"
  tranTimeout: "100ms"

redis:
  name: "user-bff"
  proto: "tcp"
  addr: "172.16.38.91:6379"
  dialTimeout: "1s"
  readTimeout: "1s"
  writeTimeout: "1s"
  idleTimeout: "10s"

http:
  addr: "0.0.0.0:8081"

grpc:
  addr: "127.0.0.1:10002"

# 注册本服务
register:
  name: "user-bff"
  addr: "注册中心地址"
  tags: ["消息服务", "message_service"]

discovers:
  msg:
    name: "msg_service"
    addr: "0.0.0.0:10002"
    dial: "3000ms"
    timeout: "5000ms"
  relation:
    name: "relation_service"
    addr: "0.0.0.0:10004"
    dial: "3000ms"
    timeout: "5000ms"
  user:
    name: "user_service"
    addr: "0.0.0.0:10003"
    dial: "3000ms"
    timeout: "5000ms"
