name: Deploy to Server

on:
  push:
    branches:
      - 'releases/**'
      - 'main'
      - 'master'
    paths:
      - 'docs/**'
      - 'interface/**'
      - 'pkg/**'
      - 'service/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            sudo -i
            cd /hitosea/coss-server/
            sudo docker-compose pull
            sudo docker-compose up -d